// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TCustomer
    {
        public TCustomer()
        {
            TCustomerOrderSheet = new HashSet<TCustomerOrderSheet>();
            TShoppingCart = new HashSet<TShoppingCart>();
        }

        public int FId { get; set; }
        public string FLastName { get; set; }
        public string FFirstName { get; set; }
        public byte FGender { get; set; }
        public string FTel { get; set; }
        public string FMobile { get; set; }
        public string FEmail { get; set; }
        public string FPassword { get; set; }
        public DateTime FBirthDate { get; set; }
        public int FPoint { get; set; }
        public bool FBlackList { get; set; }
        public string FRemark { get; set; }
        public DateTime FCreationDate { get; set; }
        public DateTime FLastUpdateDate { get; set; }

        public virtual TGender FGenderNavigation { get; set; }
        public virtual ICollection<TCustomerOrderSheet> TCustomerOrderSheet { get; set; }
        public virtual ICollection<TShoppingCart> TShoppingCart { get; set; }
    }
}