// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TGender
    {
        public TGender()
        {
            TCustomer = new HashSet<TCustomer>();
        }

        public byte FId { get; set; }
        public string FDescription { get; set; }

        public virtual ICollection<TCustomer> TCustomer { get; set; }
    }
}