// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TManager
    {
        public int FSid { get; set; }
        public string FAccount { get; set; }
        public string FPassword { get; set; }
    }
}