// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TOrderDetail
    {
        public TOrderDetail()
        {
            TProductReport = new HashSet<TProductReport>();
            TProductReview = new HashSet<TProductReview>();
            TPurchaseOrderSheet = new HashSet<TPurchaseOrderSheet>();
        }

        public int FId { get; set; }
        public int FCustomerOrderSheetId { get; set; }
        public int FProductId { get; set; }
        public int FPurchaseQuantity { get; set; }

        public virtual TCustomerOrderSheet FCustomerOrderSheet { get; set; }
        public virtual TProduct FProduct { get; set; }
        public virtual ICollection<TProductReport> TProductReport { get; set; }
        public virtual ICollection<TProductReview> TProductReview { get; set; }
        public virtual ICollection<TPurchaseOrderSheet> TPurchaseOrderSheet { get; set; }
    }
}