// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TProvider
    {
        public TProvider()
        {
            TProduct = new HashSet<TProduct>();
        }

        public int FId { get; set; }
        public string FCompanyName { get; set; }
        public string FPassword { get; set; }
        public string FTaxId { get; set; }
        public string FFax { get; set; }
        public string FOwnerName { get; set; }
        public string FOwnerTel { get; set; }
        public string FOwnerMobile { get; set; }
        public string FOwnerEmail { get; set; }
        public string FContactName { get; set; }
        public string FContactTel { get; set; }
        public string FContactMobile { get; set; }
        public string FContactEmail { get; set; }
        public string FAddress { get; set; }
        public string FBankName { get; set; }
        public string FBankDivisionName { get; set; }
        public string FBankAccountNumber { get; set; }
        public string FBankAccountName { get; set; }
        public bool FBlackList { get; set; }
        public string FRemark { get; set; }
        public DateTime FCreationDate { get; set; }
        public DateTime FLastUpdateDate { get; set; }

        public virtual ICollection<TProduct> TProduct { get; set; }
    }
}