// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TProductsTag
    {
        public int FSid { get; set; }
        public int FProductId { get; set; }
        public int FTagId { get; set; }

        public virtual TProduct FProduct { get; set; }
        public virtual TTag FTag { get; set; }
    }
}