// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FinalProject.Models
{
    public partial class TTag
    {
        public TTag()
        {
            TProductsTag = new HashSet<TProductsTag>();
        }

        public int FId { get; set; }
        public string FDescription { get; set; }

        public virtual ICollection<TProductsTag> TProductsTag { get; set; }
    }
}